<?php 
/**
 * This template displays the single Product
 *
 * @package genesis_connect_woocommerce
 * @version 0.9.8
 *
 * Note for customisers/users: Do not edit this file!
 * ==================================================
 * If you want to customise this template, copy this file (keep same name) and place the
 * copy in the child theme's woocommerce folder, ie themes/my-child-theme/woocommerce
 * (Your theme may not have a 'woocommerce' folder, in which case create one.)
 * The version in the child theme's woocommerce folder will override this template, and
 * any future updates to this plugin won't wipe out your customisations.
 *
 */

global $post;

if(isset($post->ID) && !empty($post->ID))
{
	$product_id = $post->ID;
}	

if($product_id == "4136")
{
	include_once MWB_DIRPATH."/product-templates/hubspot-template.php";
}
elseif($product_id == "9192")
{
	include_once MWB_DIRPATH."/product-templates/mautic-template.php";
}
elseif($product_id == "5367" || $product_id == "10173")
{
	include_once MWB_DIRPATH."/product-templates/product-template.php";
}
// elseif($product_id == "5847")
// {
// 	include_once MWB_DIRPATH."/product-templates/product-template-2.php";
// }
elseif($product_id == "7810")
{
	include_once MWB_DIRPATH."/product-templates/bogo-template.php";
}
elseif($product_id == "12419")
{
	include_once MWB_DIRPATH."/product-templates/dokan.php";
}
elseif($product_id == "12507")
{
	include_once MWB_DIRPATH."/product-templates/icontact-template.php";
}
elseif($product_id == "10413")
{
	include_once MWB_DIRPATH."/product-templates/swrp-template.php";
}
elseif($product_id == "10753" || $product_id == "10809")
{
	include_once MWB_DIRPATH."/product-templates/save-cart-template.php";
}
// elseif($product_id == "5829")
// {
// 	include_once MWB_DIRPATH."/product-templates/variation_master.php";
// }
// elseif($product_id == "2682")
// {
// 	include_once MWB_DIRPATH."/product-templates/variation_update_in_cart.php";
// }
else
{


/** Remove default Genesis loop */
remove_action( 'genesis_loop', 'genesis_do_loop' );

/** Remove WooCommerce breadcrumbs */
remove_action( 'woocommerce_before_main_content', 'woocommerce_breadcrumb', 20 );

/** Uncomment the below line of code to add back WooCommerce breadcrumbs */
//add_action( 'genesis_before_loop', 'woocommerce_breadcrumb', 10, 0 );

/** Remove Woo #container and #content divs */
remove_action( 'woocommerce_before_main_content', 'woocommerce_output_content_wrapper', 10 );
remove_action( 'woocommerce_after_main_content', 'woocommerce_output_content_wrapper_end', 10 );


add_action( 'genesis_loop', 'gencwooc_single_product_loop' );
/**
 * Displays single product loop
 *
 * Uses WooCommerce structure and contains all existing WooCommerce hooks
 *
 * Code based on WooCommerce 1.5.5 woocommerce_single_product_content()
 * @see woocommerce/woocommerce-template.php
 *
 * @since 0.9.0
 */
function gencwooc_single_product_loop()

{

	do_action( 'woocommerce_before_main_content' );

	// Let developers override the query used, in case they want to use this function for their own loop/wp_query
	$wc_query = false;

	// Added a hook for developers in case they need to modify the query
	$wc_query = apply_filters( 'gencwooc_custom_query', $wc_query );

	if ( ! $wc_query)
	{

		global $wp_query;

		$wc_query = $wp_query;
	}

	if ( $wc_query->have_posts() ) while ( $wc_query->have_posts() ) : $wc_query->the_post(); ?>

	<?php do_action('woocommerce_before_single_product'); ?>

	<div itemscope itemtype="http://schema.org/Product" id="product-<?php the_ID(); ?>" <?php post_class(); ?>>

		<div class="mwb_detail_page">
			<div class="mwb_aboutpro_section">	
				<div class="mwb_plugin_wrapper">
					<div class="mwb_about">
						<div class="mwb_detail_wrapper">
						    <div class="mwb_pro_title " >
								<h1><?php 
								do_action( 'woocommerce_single_product_summary' );	
								the_title();
								?></h1>
								<span class="mwb_rating"><?php echo do_shortcode('[mwb_product_rating]'); ?></span>
							</div>
							<div class="mwb_detail" >
								<?php 
								the_title( '<span itemprop="name" class="mwb_product_title_hide">', '</span>' );
								the_content();

								?>
							</div>
							<div class="mwb_product_review">
							<?php comments_template(); ?>
							</div>
						</div>

						<!-- added by umakant -->

						<?php  
						$terms = get_the_terms( get_the_ID(), 'product_cat' );
						// print_r($terms);die;

                        foreach ($terms as $term)
                        {

                            $product_cat_name = $term->slug;
                            break;
                        }
                        if ( $product_cat_name == 'product')
                        {
                        ?>
						<div class="mwb_pro_detail">
						
						    <div class="mwb_product_info">
							    <?php 
							    global $product;
								if($product->is_type('variable'))
								{
								?>

								
								<div class="mwb_excerpt">
                                <?php //the_excerpt(); ?>
                                <h3>Product Description</h3>

								<?php //echo do_shortcode('[mwb_product_price]'); ?>
									
								</div>

								<div class="mwb_price">
									<ul>
									<?php
									$codecanyon_link = get_post_meta(get_the_ID(), 'mwb_codcanyon_product_link', true);

									if(isset($codecanyon_link) && !empty($codecanyon_link))
									{
									?>
										<li><i class="fa fa-check-circle" aria-hidden="true"></i> Quality checked by Envato</li>
										<li><i class="fa fa-check-circle" aria-hidden="true"></i> Future updates</li>
										<li><i class="fa fa-check-circle" aria-hidden="true"></i> 6 months support</li>
										<?php
										}
										else{
										?>
										<li><i class="fa fa-check-circle" aria-hidden="true"></i> One Time Payment</li>
										<li><i class="fa fa-check-circle" aria-hidden="true"></i> 1 Year Free Updates</li>
										<li><i class="fa fa-check-circle" aria-hidden="true"></i> 6 Month Support</li>
									<?php
									}
									?>
									</ul>
								</div>
								<!-- <div class="mwb_price">
								<?php // echo do_shortcode('[mwb_product_support]'); ?>
								</div> -->
								<div class="mwb_price">
								<?php echo do_shortcode('[mwb_product_multiple_license]'); ?>
								</div>
								<!-- <div class="mwb_price mwb_normal_cart">
								<?php // echo do_shortcode('[mwb_product_add_to_cart]'); ?>
								</div>
								<div class="mwb_price mwb_support_cart">
								<?php // echo do_shortcode('[mwb_support_add_to_cart]'); ?>
								</div> -->
								
								<?php
								} 
								else
								{
									if($product->is_purchasable() && $product->is_in_stock())
									{
										$enable_free_download = get_post_meta( get_the_ID(), 'mwb_enable_free_product_setting', true);
										$checkouturl = wc_get_checkout_url();
										if(isset($enable_free_download) && !empty($enable_free_download) && $enable_free_download[0] == 'true')
										{
											?>
											<div class="mwb_price">

	                      					    <!-- <h4></h4> -->
	                      					    <a href="<?php echo $checkouturl ; ?>?add-to-cart=<?php echo get_the_ID();  ?>" class="mwbgetnow">Get Now</a>
                      					    
										    </div>
											<?php
										}
										else
										{
											?>
											<div class="mwb_excerpt">
		                                	<?php //the_excerpt(); ?>

											<?php echo do_shortcode('[mwb_product_price]'); ?>
											
											</div>

											<div class="mwb_price">
												<ul>
												<?php
												$codecanyon_link = get_post_meta(get_the_ID(), 'mwb_codcanyon_product_link', true);

												if(isset($codecanyon_link) && !empty($codecanyon_link))
												{
												?>
													<li><i class="fa fa-check-circle" aria-hidden="true"></i> Quality checked by Envato</li>
													<li><i class="fa fa-check-circle" aria-hidden="true"></i> Future updates</li>
													<li><i class="fa fa-check-circle" aria-hidden="true"></i> 6 months support</li>
												<?php
												}
												else
												{
												?>
													<li><i class="fa fa-check-circle" aria-hidden="true"></i> One Time Payment</li>
													<li><i class="fa fa-check-circle" aria-hidden="true"></i> Single License (For Lifetime)</li>
													<li><i class="fa fa-check-circle" aria-hidden="true"></i> 1 Year Free Updates</li>
													<li><i class="fa fa-check-circle" aria-hidden="true"></i> 6 Month Support</li>
												<?php
												}
												?>
												</ul>
											</div>
											<!-- <div class="mwb_price">
											<?php // echo do_shortcode('[mwb_product_support]'); ?>
											</div> -->
											<div class="mwb_price mwb_normal_cart">
											<?php echo do_shortcode('[mwb_product_add_to_cart]'); ?>
											</div>
										
											<!-- <div class="mwb_price mwb_support_cart">
											<?php // echo do_shortcode('[mwb_support_add_to_cart]'); ?>
											</div> -->
											<?php
										}
									}
									else
									{

									?>
										<div class="mwb_price">
										<?php echo do_shortcode(' [nf-popup id=10304] ');?>

                      					<h4>For More Information</h4>

											<button class="single_add_to_cart_button button alt quote_popup">Get Quote</button>
										</div>
										<?php
									}
								} 
								?>
							</div>

							<?php
							$mwb_hubspot_product_id = get_the_ID();
							if($mwb_hubspot_product_id == 4136 || $mwb_hubspot_product_id == 4050 || $mwb_hubspot_product_id == 4055 || $mwb_hubspot_product_id == 4087 || $mwb_hubspot_product_id == 6684)
							{	
							?>
							<div class="mwb_widget">
								<a href="https://calendly.com/umakantsharma/15min/" rel="noopener" target="_blank" class="mwb_calendy"><img src="https://makewebbetter.com/wp-content/uploads/2018/07/hubspot-umakant.png" alt="" class="aligncenter size-full wp-image-9917"></a>
							</div>
							<?php
							}

							$mwb_plugin_documentation=get_post_meta(get_the_ID(),'mwb_plugin_documentation',true);
							if(!empty($mwb_plugin_documentation))
							{	
							?>

							<div class="mwb_widget">
								<h3>Documentation</h3>
								<?php 
								if(isset($mwb_plugin_documentation) && !empty($mwb_plugin_documentation))
								{
								?>
								<?php echo do_shortcode('[mwb_product_documentation]'); ?>
								<?php
								}
								?>
							</div>

							<?php
							}	
							$mwb_plugin_front_end_demo=get_post_meta(get_the_ID(),'mwb_plugin_front_end_demo',true);
							$mwb_plugin_back_end_demo=get_post_meta(get_the_ID(),'mwb_plugin_back_end_demo',true);
							if($mwb_plugin_front_end_demo != "" || $mwb_plugin_back_end_demo != "")
							{	
							?>
							<div class="mwb_widget">
								<h3>Demo</h3>
								<ul>
									<?php if(isset($mwb_plugin_front_end_demo) && !empty($mwb_plugin_front_end_demo))
									{
							    	?>
									<li><a href="<?php echo get_post_meta(get_the_ID(), 'mwb_plugin_front_end_demo', true);?>" target="_blank">Frontend Demo</a></li>
									<?php
									}
									if(isset($mwb_plugin_back_end_demo) && !empty($mwb_plugin_back_end_demo))
									{
							    	?>
									<li><a href="<?php echo get_post_meta(get_the_ID(), 'mwb_plugin_back_end_demo', true);?>" target="_blank">Backend Demo</a></li>
									<?php
									}
									?>
								</ul>
							</div>
							
							
							<?php
							}
							$mwb_compatible_with=get_post_meta(get_the_ID(),'mwb_compatible_with',true);
							$mwb_compatible_browsers=get_post_meta(get_the_ID(),'mwb_compatible_browsers',true);
							$mwb_files_included=get_post_meta(get_the_ID(),'mwb_files_included',true);
							$mwb_minimum_php_version=get_post_meta(get_the_ID(),'mwb_minimum_php_version',true);
							$mwb_version=get_post_meta(get_the_ID(),'mwb_version',true);
							$mwb_released=get_post_meta(get_the_ID(),'mwb_released',true);
							$mwb_translation_ready=get_post_meta(get_the_ID(),'mwb_translation_ready',true);
							$mwb_languages=get_post_meta(get_the_ID(),'mwb_languages',true);
							?>

							<div class="mwb_widget">
								<h3 class="quick-info-title">QUICK INFO</h3>
								<table>
								<?php if(isset($mwb_compatible_with) && !empty($mwb_compatible_with))
								{
							    ?>
								<tr><td><strong>Compatible With</strong></td> <td><?php the_field('mwb_compatible_with'); ?></td></tr>
								<?php
								}
								if(isset($mwb_compatible_browsers) && !empty($mwb_compatible_browsers))
								{
							    ?>
								<tr><td><strong>Compatible Browsers</strong></td> <td><?php the_field('mwb_compatible_browsers'); ?></td></tr>
								<?php
								}
								if(isset($mwb_files_included) && !empty($mwb_files_included))
								{
							    ?>

								<tr><td><strong>Files Included</strong></td><td><?php the_field('mwb_files_included'); ?></td></tr>
								<?php
								}
								if(isset($mwb_minimum_php_version) && !empty($mwb_minimum_php_version))
								{
							    ?>
								<tr><td><strong>Minimum PHP version</strong></td><td><?php the_field('mwb_minimum_php_version'); ?></td></tr>
								<?php
								}
								if(isset($mwb_version) && !empty($mwb_version))
								{
							    ?>
								<tr><td><strong>Version</strong> </td><td><?php the_field('mwb_version'); ?></td></tr>
								<?php
								}
								if(isset($mwb_released) && !empty($mwb_released))
								{
							    ?>
								<tr><td><strong>Released</strong></td><td> <?php
									echo date("M d, Y", strtotime($mwb_released));
								?></td></tr>
								<?php
								}
								if(isset( $mwb_translation_ready) && !empty($mwb_translation_ready))
								{
							    ?>
								<tr><td><strong>Translation ready</strong></td><td><?php the_field('mwb_translation_ready'); ?></td></tr>
								<?php
								}
								if(isset($mwb_languages) && !empty($mwb_languages))
								{
							    ?>
								<tr><td><strong>Languages</strong></td><td> <?php the_field('mwb_languages'); ?></td></tr>
								<?php
								}
								?>
								</table>
							</div>
							<?php echo do_shortcode('[mwb_product_meta]'); ?>
						</div>

						<!-- umakant changes -->

						<?php
						}

                        if ($product_cat_name == 'services')
                        {
                        ?>
                            <div class="mwb_pro_detail" >
	                            <div class="mwb_product_info">
	                            <?php
	                            $enable_free_download = get_post_meta( get_the_ID(), 'mwb_enable_free_product_setting', true);
								$checkouturl = wc_get_checkout_url();
								if(isset($enable_free_download) && !empty($enable_free_download) && $enable_free_download[0] == 'true')
								{
									?>
									<div class="mwb_price">

                  					    <!-- <h4></h4> -->
                  					    <a href="<?php echo $checkouturl ; ?>?add-to-cart=<?php echo get_the_ID();  ?>" class="mwbgetnow">Get Now</a>
              					    
								    </div>
									<?php
								}
								else
								{
									?>
	                                <div class="mwb_excerpt">
	                                <?php //the_excerpt(); ?>

	                                <?php echo do_shortcode('[mwb_product_price]'); ?>
	                                    
	                                </div>

	                                <div class="mwb_price">
	                                <?php echo do_shortcode('[mwb_product_add_to_cart]'); ?>
	                                </div>
									
									<?php
								}
	                            ?>  
	                                
	                            </div>

                            	<div class="mwb_widget">
									<a href="https://calendly.com/shubhamnigam/30min/" rel="noopener" target="_blank" class="mwb_calendy"><img src="https://makewebbetter.com/wp-content/uploads/2018/07/shubham-service.png" alt="" class="aligncenter size-full wp-image-9917"></a>
								</div>

								<div class="service-sidebar-widget">
	                            <?php echo do_shortcode('[mwb_microservice_related]'); ?>
	                            </div>

	                            <div class="service-sidebar-widget">
	                            <p style="text-align: center;"><strong>Is your Website Secured!</strong></p>
	                            <p style="text-align: center;"><strong>Want to secure your website?</strong></p>
	                            <p style="text-align: center;"><a href="javascript:$zopim.livechat.window.show();"><button style="background-color: #0a5479;">Let's talk</button></a></p>
	                            </div>
	                            <div class="service-sidebar-widget">
	                            <p style="text-align: center;"><strong><span class="nodeLabelBox repTarget " role="treeitem"><span class="nodeText editable "><span class=" ">Connect with Hubspot</span></span></span></strong></p>
	                            <img class="aligncenter" style="border: 0px;" src="<?php echo site_url(); ?>/wp-content/uploads/2018/03/sprocket2.png" alt="" width="125" height="125" />
	                            <p style="text-align: center;"><a href="<?php echo site_url(); ?>/product/hubspot-woocommerce-integration-pro/" target="_blank" rel="noopener"><button style="background-color: #0a5479;">Connect Now</button></a></p>
	                            </div>
	                            <div class="service-sidebar-widget">
	                            <p style="text-align: center;"><strong>Drag and drop, responsive form builder</strong></p>
	                            
	                            <p style="text-align: center;"><a href="https://calderaforms.com/?thnx=96" target="_blank" rel="noopener"><button style="background-color: #0a5479;">Get Your Plugin now!</button></a></p>
	                            </div>
	                            <div class="service-sidebar-widget">
	                            <p style="text-align: center;"><strong><span class="nodeLabelBox repTarget " role="treeitem"><span class="nodeText editable "><span class=" ">Secure  your website today!
	                            </span></span></span></strong></p>
	                            <img class="aligncenter" style="border: 0px;" src="<?php echo site_url(); ?>/wp-content/uploads/2017/11/jetpack-logo_360.jpg" alt="" width="139" height="139" />
	                            <p style="text-align: center;"><a href="https://jetpack.com/?aff=3190" target="_blank" rel="noopener"><button style="background-color: #0a5479;">Get it now</button></a></p>
	                            </div>
                            
                            </div>
                        <?php 
                        } 
                        if ($product_cat_name == 'theme' || $product_cat_name == 'snippet' || $product_cat_name == 'template')
                        {
                        ?>
                        	<div class="mwb_pro_detail" >
	                            <div class="mwb_product_info">
	                            <?php
	                            $enable_free_download = get_post_meta( get_the_ID(), 'mwb_enable_free_product_setting', true);
								$checkouturl = wc_get_checkout_url();
								if(isset($enable_free_download) && !empty($enable_free_download) && $enable_free_download[0] == 'true')
								{
									?>
									<div class="mwb_price">

                  					    <!-- <h4></h4> -->
                  					    <a href="<?php echo $checkouturl ; ?>?add-to-cart=<?php echo get_the_ID();  ?>" class="mwbgetnow">Get Now</a>
              					    
								    </div>
									<?php
								}
								else
								{
									?>
		                            <div class="mwb_excerpt">
		                            <?php //the_excerpt(); ?>

		                            <?php echo do_shortcode('[mwb_product_price]'); ?>
		                                
		                            </div>

		                            <div class="mwb_price">
		                            <ul>
		                            	<li><i class="fa fa-check-circle" aria-hidden="true"></i> One Time Payment</li>
		                            	<li><i class="fa fa-check-circle" aria-hidden="true"></i> Single License (For Lifetime)</li>
		                            	<li><i class="fa fa-check-circle" aria-hidden="true"></i> 6 Months Free Updates</li>
		                            	<li><i class="fa fa-check-circle" aria-hidden="true"></i> 6 Months Support</li>
		                            	
		                            </ul>
		                            </div>

		                            <div class="mwb_price">
		                            <?php echo do_shortcode('[mwb_product_add_to_cart]'); ?>
		                            </div>
									<?php
								}
	                            ?>
		                                
		                        </div>

                            	<?php
                            	$mwb_plugin_documentation=get_post_meta(get_the_ID(),'mwb_plugin_documentation',true);
                            	if(!empty($mwb_plugin_documentation))
                            	{	
                            	?>

                            		<div class="mwb_widget">
                            			<h3>Documentation</h3>
                            			<?php 
                            			

                            			if(isset($mwb_plugin_documentation) && !empty($mwb_plugin_documentation)){
                            			?>
                            			<?php echo do_shortcode('[mwb_product_documentation]'); ?>
                            			<?php } ?>
                            		</div>

                            		<?php
                            	}	
                            	$mwb_plugin_front_end_demo=get_post_meta(get_the_ID(),'mwb_plugin_front_end_demo',true);
                            	$mwb_plugin_back_end_demo=get_post_meta(get_the_ID(),'mwb_plugin_back_end_demo',true);
                            	if($mwb_plugin_front_end_demo != "" || $mwb_plugin_back_end_demo != "")
                            	{	
                            	?>
                            	<div class="mwb_widget">
                            		<h3>Demo</h3>
                            		<ul>
                            		<?php if(isset($mwb_plugin_front_end_demo) && !empty($mwb_plugin_front_end_demo))
                            		{
                            	    ?>
                            			<li><a href="<?php echo get_post_meta(get_the_ID(), 'mwb_plugin_front_end_demo', true);?>" target="_blank">Frontend Demo</a></li>
                            		<?php
                            		}
                            		if(isset($mwb_plugin_back_end_demo) && !empty($mwb_plugin_back_end_demo))
                            		{
                            	    ?>
                            			<li><a href="<?php echo get_post_meta(get_the_ID(), 'mwb_plugin_back_end_demo', true);?>" target="_blank">Backend Demo</a></li>
                            		<?php
                            		}
                            		?>
                            		</ul>
                            	</div>
                            	
                            	<?php
                            	}
                            	$mwb_compatible_with=get_post_meta(get_the_ID(),'mwb_compatible_with',true);
                            	$mwb_compatible_browsers=get_post_meta(get_the_ID(),'mwb_compatible_browsers',true);
                            	$mwb_files_included=get_post_meta(get_the_ID(),'mwb_files_included',true);
                            	$mwb_minimum_php_version=get_post_meta(get_the_ID(),'mwb_minimum_php_version',true);
                            	$mwb_version=get_post_meta(get_the_ID(),'mwb_version',true);
                            	$mwb_released=get_post_meta(get_the_ID(),'mwb_released',true);
                            	$mwb_translation_ready=get_post_meta(get_the_ID(),'mwb_translation_ready',true);
                            	$mwb_languages=get_post_meta(get_the_ID(),'mwb_languages',true);
                            	?>

                            	<div class="mwb_widget">
                            		<h3 class="quick-info-title">QUICK INFO</h3>
                            		<table>
	                            		<?php if(isset($mwb_compatible_with) && !empty($mwb_compatible_with))
	                            		{
	                            	    ?>
	                            		<tr><td><strong>Compatible With</strong></td> <td><?php the_field('mwb_compatible_with'); ?></td></tr>
	                            		<?php
	                            		}
	                            		if(isset($mwb_compatible_browsers) && !empty($mwb_compatible_browsers))
	                            		{
	                            	    ?>
	                            		<tr><td><strong>Compatible Browsers</strong></td> <td><?php the_field('mwb_compatible_browsers'); ?></td></tr>
	                            		<?php
	                            		}
	                            		if(isset($mwb_files_included) && !empty($mwb_files_included))
	                            		{
	                            	    ?>
	                            		<tr><td><strong>Files Included</strong></td><td><?php the_field('mwb_files_included'); ?></td></tr>
	                            		<?php
	                            		}
	                            		if(isset($mwb_minimum_php_version) && !empty($mwb_minimum_php_version))
	                            		{
	                            	    ?>
	                            		<tr><td><strong>Minimum PHP version</strong></td><td><?php the_field('mwb_minimum_php_version'); ?></td></tr>
	                            		<?php
	                            		}
	                            		if(isset($mwb_version) && !empty($mwb_version))
	                            		{
	                            	    ?>
	                            		<tr><td><strong>Version</strong> </td><td><?php the_field('mwb_version'); ?></td></tr>
	                            		<?php
	                            		}
	                            		if(isset($mwb_released) && !empty($mwb_released))
	                            		{
	                            	    ?>
	                            		<tr><td><strong>Released</strong></td><td> <?php 
	                            			echo date("M d, Y", strtotime($mwb_released));
	                            		?></td></tr>
	                            		<?php
	                            		}
	                            		if(isset( $mwb_translation_ready) && !empty($mwb_translation_ready))
	                            		{
	                            	    ?>
	                            		<tr><td><strong>Translation ready</strong></td><td><?php the_field('mwb_translation_ready'); ?></td></tr>
	                            		<?php
	                            		}
	                            		if(isset($mwb_languages) && !empty($mwb_languages))
	                            		{
	                            	    ?>
	                            		<tr><td><strong>Languages</strong></td><td> <?php the_field('mwb_languages'); ?></td></tr>
	                            		<?php
	                            		}
	                            		?>
                            		</table>
                            	</div>
                            	<?php echo do_shortcode('[mwb_product_meta]'); ?>

                            	<?php /*<div class="mwb_widget">
                            		 echo do_shortcode("[thrive_leads id='7730']"); 
                            	</div>
                            	*/
                            	?>
                            </div>

                        <?php
                        }
                        if ($product_cat_name == 'icon')
                        {
                    	?>
                        	<div class="mwb_pro_detail" >
	                            <div class="mwb_product_info">
	                            <?php
	                            $enable_free_download = get_post_meta( get_the_ID(), 'mwb_enable_free_product_setting', true);
								$checkouturl = wc_get_checkout_url();
								if(isset($enable_free_download) && !empty($enable_free_download) && $enable_free_download[0] == 'true')
								{
									?>
									<div class="mwb_price">

                  					    <!-- <h4></h4> -->
                  					    <a href="<?php echo $checkouturl ; ?>?add-to-cart=<?php echo get_the_ID();  ?>" class="mwbgetnow">Get Now</a>
              					    
								    </div>
									<?php
								}
								else
								{
									?>
		                            <div class="mwb_excerpt">
		                            <?php //the_excerpt(); ?>

		                            <?php echo do_shortcode('[mwb_product_price]'); ?>
		                                
		                            </div>

		                            <div class="mwb_price">
		                            <ul>
		                            	<li><i class="fa fa-check-circle" aria-hidden="true"></i> One Time Payment</li>
		                            	<li><i class="fa fa-check-circle" aria-hidden="true"></i> No License</li>
		                            	<li><i class="fa fa-check-circle" aria-hidden="true"></i> 1 Year Support</li>
		                            	
		                            </ul>
		                            </div>

		                            <div class="mwb_price">
		                            <?php echo do_shortcode('[mwb_product_add_to_cart]'); ?>
		                            </div>
									<?php
								}
	                            ?> 
	                            </div>

	                            <?php
	                            
	                            $mwb_high_resolution=get_post_meta(get_the_ID(),'mwb_high_resolution',true);
	                            $mwb_layered=get_post_meta(get_the_ID(),'mwb_layered',true);
	                            $mwb_icon_files_includes=get_post_meta(get_the_ID(),'mwb_icon_files_includes',true);
	                            $mwb_created_in_adobe_version=get_post_meta(get_the_ID(),'mwb_created_in_adobe_version',true);
	                            $mwb_minimum_adobe_version_requirement=get_post_meta(get_the_ID(),'mwb_minimum_adobe_version_requirement',true);
	                            
	                            ?>

	                            <div class="mwb_widget">
	                            	<h3 class="quick-info-title">QUICK INFO</h3>
	                            	<table>
		                            	<?php 
		                            	if(isset($mwb_high_resolution) && !empty($mwb_high_resolution))
		                            	{
		                                ?>
		                            	<tr><td><strong>High Resolution</strong></td> <td><?php the_field('mwb_high_resolution'); ?></td></tr>
		                            	<?php
		                            	}
		                            	if(isset($mwb_layered) && !empty($mwb_layered))
		                            	{
		                                ?>
		                            	<tr><td><strong>Layered</strong></td> <td><?php the_field('mwb_layered'); ?></td></tr>
		                            	<?php
		                            	}
		                            	if(isset($mwb_icon_files_includes) && !empty($mwb_icon_files_includes))
		                            	{
		                                ?>
		                            	<tr><td><strong>File Includes</strong></td><td><?php the_field('mwb_icon_files_includes'); ?></td></tr>
		                            	<?php
		                            	}
		                            	if(isset($mwb_created_in_adobe_version) && !empty($mwb_created_in_adobe_version))
		                            	{
		                                ?>
		                            	<tr><td><strong>Created In Adobe Version</strong></td><td><?php the_field('mwb_created_in_adobe_version'); ?></td></tr>
		                            	<?php
		                            	}
		                            	if(isset($mwb_minimum_adobe_version_requirement) && !empty($mwb_minimum_adobe_version_requirement))
		                            	{
		                                ?>
		                            	<tr><td><strong>Minimum Adobe Version Requirement</strong> </td><td><?php the_field('mwb_minimum_adobe_version_requirement'); ?></td></tr>
		                            	<?php
		                            	}
		                                ?>
	                            	</table>
	                            </div>
	                            <div class="mwb_widget-img">
		                            <a href="<?php echo site_url(); ?>/contact-us/" target="_blank">
		                            <img src="<?php echo site_url(); ?>/wp-content/uploads/2018/06/contact_me.jpg" alt="" width="400" height="400" />
		                            </a>
	                            </div>
	                        </div>
                        <?php
                        }	  	 
                        ?>
					</div>
				</div>
			</div>
		</div>

		<?php // do_action( 'woocommerce_before_single_product_summary' ); ?>

		<?php 
		//do_action( 'woocommerce_after_single_product_summary' ); ?>
		
		<section class="related products mwb_related_pro">
		</section>

	</div>

	<?php 
	do_action( 'woocommerce_after_single_product' );

	endwhile;

	do_action( 'woocommerce_after_main_content' );
	}

	genesis();
}